kind: PersistentVolume
apiVersion: v1
metadata:
  name: train-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/rootkrause/Documents/tensorflow_test/volume"
